// apps/vue/App.vue
<script setup lang="ts">
import { computed, nextTick, onBeforeUnmount, onMounted, ref, watch } from 'vue';
import { AudioGrid, ModernMediasfuGeneric, useMediasfuHeadless } from 'mediasfu-vue';
import { createSession, endSession, joinSession, listSessions, type CallSession } from './src/sessionApi';

type Identity = { userId: string; displayName: string };
type CallConfig =
  | { mode: 'create'; targetUserId: string; callType: 'audio' | 'video' }
  | { mode: 'join'; session: CallSession; callType: 'audio' | 'video' };
type VideoSurface = { stream: MediaStream; local: boolean; screen: boolean; key: string; label: string };

const room = useMediasfuHeadless();
const identity = ref<Identity | null>(loadIdentity());
const userId = ref('');
const displayName = ref('');
const targetUserId = ref('');
const sessions = ref<CallSession[]>([]);
const call = ref<CallConfig | null>(null);
const activeSession = ref<CallSession | null>(null);
const notice = ref('');
const mediaStarted = ref(false);
const roleApplied = ref(false);
const testCanvas = ref<HTMLCanvasElement | null>(null);
const demoActive = ref(false);
const focusIndex = ref(0);
const miniOffset = ref({ x: 0, y: 0 });
const mediaStage = ref<HTMLElement | null>(null);
const previewStrip = ref<HTMLElement | null>(null);
let dragState: { pointerId: number; startX: number; startY: number; originX: number; originY: number } | null = null;
let demoTimer: number | undefined;
let demoStream: MediaStream | undefined;
let pollTimer: number | undefined;

const incoming = computed(() => sessions.value.find((item) =>
  item.status === 'ringing' && item.targetUserId === identity.value?.userId,
) ?? null);
const peerName = computed(() => call.value?.mode === 'create'
  ? call.value.targetUserId
  : call.value?.session.hostUserId ?? 'Contact');
const surfaces = computed<VideoSurface[]>(() => {
  const next: VideoSurface[] = [];
  const screen = room.screenShare.value;
  const remote = room.remoteVideos.value[0];
  const local = room.localVideo.value;
  if (screen.stream) next.push({ stream: screen.stream, local: screen.isLocal, screen: true, key: `screen-${screen.stream.id}`, label: screen.isLocal ? 'Your screen' : `${peerName.value}'s screen` });
  if (remote?.stream) next.push({ stream: remote.stream, local: false, screen: false, key: `remote-${remote.producerId || remote.stream.id}`, label: peerName.value });
  if (local) next.push({ stream: local, local: true, screen: false, key: `local-${local.id}`, label: 'You' });
  return next;
});
const screenActive = computed(() => surfaces.value[0]?.screen === true);
const normalizedFocus = computed(() => screenActive.value ? 0 : Math.min(focusIndex.value, Math.max(surfaces.value.length - 1, 0)));
const primary = computed(() => surfaces.value[normalizedFocus.value] ?? null);
const previews = computed(() => surfaces.value.filter((_, index) => index !== normalizedFocus.value));
const canSwapFocus = computed(() => !screenActive.value && surfaces.value.length > 1);
const preJoinOptions = computed<any>(() => {
  if (!identity.value || !call.value) return undefined;
  return call.value.mode === 'join'
    ? { action: 'join', meetingID: call.value.session.meetingId, userName: identity.value.displayName }
    : { action: 'create', duration: 30, capacity: 2, eventType: 'conference', userName: identity.value.displayName };
});

function loadIdentity(): Identity | null {
  try {
    const value = JSON.parse(localStorage.getItem('mediasfu-familiar-identity') || 'null');
    return value?.userId && value?.displayName ? value : null;
  } catch { return null; }
}

function saveIdentity() {
  const safeId = userId.value.trim();
  const safeName = displayName.value.trim();
  if (!/^[A-Za-z0-9_-]{2,64}$/.test(safeId) || !/^[A-Za-z0-9]{2,10}$/.test(safeName)) {
    notice.value = 'Use a 2–64 character ID and a 2–10 character alphanumeric display name.';
    return;
  }
  identity.value = { userId: safeId, displayName: safeName };
  localStorage.setItem('mediasfu-familiar-identity', JSON.stringify(identity.value));
  void refreshSessions();
}

async function refreshSessions() {
  if (!identity.value) return;
  try {
    sessions.value = (await listSessions(identity.value.userId))
      .sort((a, b) => Date.parse(b.updatedAt) - Date.parse(a.updatedAt));
  } catch (error) {
    notice.value = error instanceof Error ? error.message : 'Call service unavailable.';
  }
}

function begin(callType: 'audio' | 'video') {
  if (!identity.value || !/^[A-Za-z0-9_-]{2,64}$/.test(targetUserId.value.trim())) {
    notice.value = 'Choose a valid contact ID.';
    return;
  }
  notice.value = '';
  activeSession.value = null;
  room.updateSourceParameters({});
  mediaStarted.value = false;
  roleApplied.value = false;
  call.value = { mode: 'create', targetUserId: targetUserId.value.trim(), callType };
}

function accept(session: CallSession) {
  notice.value = '';
  activeSession.value = session;
  room.updateSourceParameters({});
  mediaStarted.value = false;
  roleApplied.value = false;
  call.value = { mode: 'join', session, callType: 'video' };
}

async function decline(session: CallSession) {
  if (!identity.value) return;
  try { await endSession(session.id, identity.value.userId, 'declined'); }
  catch (error) { notice.value = error instanceof Error ? error.message : 'Could not decline call.'; }
  await refreshSessions();
}

async function createMediaSFURoom(): Promise<any> {
  if (!identity.value || call.value?.mode !== 'create') return { success: false, data: { error: 'Call setup expired.' } };
  try {
    const response = await createSession({ hostUserId: identity.value.userId, targetUserId: call.value.targetUserId, displayName: identity.value.displayName });
    activeSession.value = response.session;
    await refreshSessions();
    return { success: true, data: response.data };
  } catch (error) {
    const message = error instanceof Error ? error.message : 'Could not start call.';
    notice.value = message;
    return { success: false, data: { error: message } };
  }
}

async function joinMediaSFURoom(): Promise<any> {
  if (!identity.value || call.value?.mode !== 'join') return { success: false, data: { error: 'Call invitation expired.' } };
  try {
    const response = await joinSession({ sessionId: call.value.session.id, userId: identity.value.userId, displayName: identity.value.displayName });
    activeSession.value = response.session;
    await refreshSessions();
    return { success: true, data: response.data };
  } catch (error) {
    const message = error instanceof Error ? error.message : 'Could not accept call.';
    notice.value = message;
    return { success: false, data: { error: message } };
  }
}

function updateSourceParameters(parameters: any) {
  room.updateSourceParameters(parameters || {});
  if (!call.value) return;
  if (!roleApplied.value && typeof parameters?.updateIslevel === 'function') {
    parameters.updateIslevel(call.value.mode === 'create' ? '2' : '1');
    roleApplied.value = true;
  }
}

function clampMiniOffset(offset: { x: number; y: number }) {
  const stage = mediaStage.value?.getBoundingClientRect();
  const mini = previewStrip.value?.getBoundingClientRect();
  if (!stage || !mini) return { x: 0, y: 0 };
  const gap = 14;
  const baseLeft = Math.max(stage.width - mini.width - gap, 0);
  const clamp = (value: number, minimum: number, maximum: number) => Math.min(Math.max(value, minimum), maximum);
  return { x: clamp(offset.x, -baseLeft, gap), y: clamp(offset.y, -gap, Math.max(stage.height - mini.height - gap, -gap)) };
}

function measurePreview() { miniOffset.value = clampMiniOffset(miniOffset.value); }
function swapFocus() {
  if (!canSwapFocus.value) return;
  focusIndex.value = focusIndex.value === 0 ? 1 : 0;
}
function beginMiniDrag(event: PointerEvent) {
  dragState = { pointerId: event.pointerId, startX: event.clientX, startY: event.clientY, originX: miniOffset.value.x, originY: miniOffset.value.y };
  (event.currentTarget as HTMLElement)?.setPointerCapture?.(event.pointerId);
  event.preventDefault();
}
function moveMini(event: PointerEvent) {
  if (!dragState || dragState.pointerId !== event.pointerId) return;
  miniOffset.value = clampMiniOffset({ x: dragState.originX + event.clientX - dragState.startX, y: dragState.originY + event.clientY - dragState.startY });
}
function endMiniDrag(event: PointerEvent) {
  if (!dragState || dragState.pointerId !== event.pointerId) return;
  (event.currentTarget as HTMLElement)?.releasePointerCapture?.(event.pointerId);
  dragState = null;
}

watch([screenActive, () => surfaces.value.length], ([sharing, count]) => {
  if (sharing || focusIndex.value >= Number(count)) focusIndex.value = 0;
  void nextTick(measurePreview);
});

watch(() => room.ready.value, async (ready) => {
  if (!ready || !call.value || mediaStarted.value) return;
  mediaStarted.value = true;
  const actions = [room.controls.toggleMic()];
  if (call.value.callType === 'video') actions.push(room.controls.toggleCamera());
  const results = await Promise.all(actions);
  const failed = results.find((item) => !item.ok);
  if (failed) notice.value = failed.error;
});

async function run(action: () => Promise<{ ok: boolean; error: string }>) {
  const result = await action();
  if (!result.ok) notice.value = result.error;
}

async function toggleDemoVideo() {
  if (demoActive.value) {
    if (demoTimer) window.clearInterval(demoTimer);
    demoTimer = undefined;
    demoStream?.getTracks().forEach((track) => track.stop());
    demoStream = undefined;
    const result = await room.produce.stop('video');
    demoActive.value = false;
    if (!result.ok) notice.value = result.error;
    return;
  }
  const canvas = testCanvas.value;
  const context = canvas?.getContext('2d');
  if (!canvas || !context) { notice.value = 'The media test canvas is unavailable.'; return; }
  let frame = 0;
  const draw = () => {
    frame += 1;
    const hue = (frame * 2) % 360;
    const gradient = context.createLinearGradient(0, 0, canvas.width, canvas.height);
    gradient.addColorStop(0, `hsl(${hue} 50% 13%)`);
    gradient.addColorStop(1, `hsl(${(hue + 70) % 360} 74% 38%)`);
    context.fillStyle = gradient; context.fillRect(0, 0, canvas.width, canvas.height);
    context.fillStyle = '#effff7'; context.font = '800 72px Inter, sans-serif';
    context.fillText('MediaSFU live media', 76, 250);
    context.font = '500 34px Inter, sans-serif';
    context.fillText(`${identity.value?.displayName || 'Caller'} · Vue WebRTC producer`, 80, 320);
    context.beginPath(); context.arc(130 + ((frame * 9) % 980), 520, 54, 0, Math.PI * 2);
    context.fillStyle = '#5bf0a4'; context.fill();
  };
  draw(); demoTimer = window.setInterval(draw, 100);
  const result = await room.produce.canvas(canvas, 15);
  if (!result.ok) {
    if (demoTimer) window.clearInterval(demoTimer);
    demoTimer = undefined; notice.value = result.error; return;
  }
  demoStream = result.stream ?? undefined;
  demoActive.value = true;
  notice.value = '';
}

async function finish() {
  try {
    if (demoActive.value) await toggleDemoVideo();
    if (room.ready.value) await room.controls.leave();
    if (activeSession.value && identity.value) await endSession(activeSession.value.id, identity.value.userId);
  } catch (error) { notice.value = error instanceof Error ? error.message : 'Call cleanup failed.'; }
  call.value = null;
  activeSession.value = null;
  room.updateSourceParameters({});
  await refreshSessions();
}

onMounted(() => {
  void refreshSessions();
  pollTimer = window.setInterval(refreshSessions, 1800);
  window.addEventListener('resize', measurePreview);
});
onBeforeUnmount(() => {
  if (pollTimer) window.clearInterval(pollTimer);
  if (demoTimer) window.clearInterval(demoTimer);
  demoStream?.getTracks().forEach((track) => track.stop());
  if (room.ready.value) void room.controls.leave();
  window.removeEventListener('resize', measurePreview);
});
</script>

<template>
  <main v-if="!identity" class="onboarding">
    <section class="glass lobby">
      <span class="brand">MediaSFU Familiar</span><h1>Your calls, without meeting codes.</h1>
      <p>Choose an identity for this local demonstration. A production app replaces this with authenticated accounts.</p>
      <label>Your user ID<input v-model="userId" autocomplete="username" placeholder="alex" /></label>
      <label>Display name<input v-model="displayName" maxlength="10" placeholder="Alex" /></label>
      <button class="primary" @click="saveIdentity">Continue</button><p v-if="notice" class="error">{{ notice }}</p>
    </section>
  </main>
  <main v-else-if="!call" class="home">
    <header><div><span class="brand">MediaSFU Familiar</span><h1>Calls</h1></div><div class="avatar">{{ identity.displayName.slice(0, 2).toUpperCase() }}</div></header>
    <section v-if="incoming" class="incoming glass">
      <span class="eyebrow">Incoming call</span><h2>{{ incoming.displayName || incoming.hostUserId }}</h2><p>{{ incoming.hostUserId }} is calling securely.</p>
      <div class="actions"><button @click="decline(incoming)">Decline</button><button class="primary" @click="accept(incoming)">Accept</button></div>
    </section>
    <section class="glass dialer"><label>Call a contact<input v-model="targetUserId" placeholder="Contact user ID" /></label><div class="actions"><button @click="begin('audio')">Audio call</button><button class="primary" @click="begin('video')">Video call</button></div></section>
    <section class="history"><div class="section-title"><h2>Recent calls</h2><span>{{ sessions.length }}</span></div>
      <article v-for="session in sessions" :key="session.id" class="session-row">
        <div class="avatar small">{{ (session.hostUserId === identity.userId ? session.targetUserId : session.hostUserId).slice(0, 2).toUpperCase() }}</div>
        <div><strong>{{ session.hostUserId === identity.userId ? session.targetUserId : session.hostUserId }}</strong><small>{{ session.status }} · {{ new Date(session.updatedAt).toLocaleString() }}</small></div>
      </article><p v-if="!sessions.length" class="muted">No calls yet. Choose a contact to begin.</p>
    </section><p v-if="notice" class="error toast">{{ notice }}</p>
  </main>
  <main v-else class="call-shell">
    <ModernMediasfuGeneric :key="activeSession?.id || `${call.mode}-${peerName}`" :return-u-i="false"
      :source-parameters="room.sourceParameters" :update-source-parameters="updateSourceParameters"
      :no-u-i-pre-join-options="preJoinOptions" :create-media-s-f-u-room="createMediaSFURoom"
      :join-media-s-f-u-room="joinMediaSFURoom" @media-changed="room.onMediaChanged" />
    <header><div class="avatar">{{ peerName.slice(0, 2).toUpperCase() }}</div><div><strong>{{ peerName }}</strong><small>{{ room.ready.value ? `${room.participants.value.length} connected` : room.readiness.value.reason }}</small></div></header>
    <section ref="mediaStage" class="media-stage" :class="{ screen: primary?.screen }" :data-focus-index="normalizedFocus">
      <button v-if="primary" type="button" class="main-media" @dblclick.prevent="swapFocus" aria-label="Main call media. Double-click or double-tap to swap with the mini preview."><video :srcObject="primary.stream" :muted="primary.local" autoplay playsinline :class="{ local: primary.local, screen: primary.screen }" /></button>
      <section v-else class="empty"><div class="avatar hero">{{ peerName.slice(0, 2).toUpperCase() }}</div><strong>{{ room.ready.value ? 'Audio call' : 'Connecting securely…' }}</strong></section>
      <div v-if="previews.length" ref="previewStrip" class="media-previews" :style="{ transform: `translate3d(${miniOffset.x}px, ${miniOffset.y}px, 0)` }" @pointerdown="beginMiniDrag" @pointermove="moveMini" @pointerup="endMiniDrag" @pointercancel="endMiniDrag">
        <button v-for="(surface, index) in previews" :key="surface.key" type="button" class="mini-media" @dblclick.prevent="index === 0 && swapFocus()" @click="!screenActive && (focusIndex = surfaces.indexOf(surface))" :aria-label="index === 0 ? 'Mini call media. Double-click or double-tap to swap with the main media.' : `Focus call preview ${index + 1}`"><video :srcObject="surface.stream" :muted="surface.local" autoplay playsinline :class="{ local: surface.local }" /><span>{{ surface.label }}</span></button>
        <i class="preview-grip" aria-hidden="true">⋮⋮</i>
      </div>
    </section>
    <p v-if="previews.length" class="gesture-hint">Double-tap to swap views · Drag the small view to move it</p>
    <p v-if="notice" class="error">{{ notice }}</p>
    <nav><button :disabled="!room.ready.value" @click="run(room.controls.toggleMic)">Mic</button><button :disabled="!room.ready.value" @click="run(room.controls.toggleCamera)">Camera</button><button :disabled="!room.ready.value" @click="run(room.controls.toggleScreenShare)">Share</button><button :disabled="!room.ready.value" @click="toggleDemoVideo">{{ demoActive ? 'Stop test' : 'Test media' }}</button><button class="end" @click="finish">End</button></nav>
    <p class="test-note">“Test media” publishes an animated canvas through the real room for repeatable two-browser verification.</p>
    <div class="remote-audio" aria-hidden="true"><AudioGrid :components-to-render="room.audioComponents.value" /></div>
    <canvas ref="testCanvas" width="1280" height="720" aria-hidden="true" class="test-canvas" />
  </main>
</template>

<style>
*{box-sizing:border-box}body{margin:0;background:#eef4f0;color:#18372b;font-family:Inter,ui-sans-serif,system-ui,-apple-system,sans-serif}button,input{font:inherit}button{cursor:pointer;border:0;border-radius:999px;padding:.85rem 1.2rem;background:#e3ece7;color:#15382a;font-weight:800}button:disabled{opacity:.45;cursor:not-allowed}.primary{background:#25d366;color:#052d1d}.brand,.eyebrow{color:#168c4a;font-size:.75rem;letter-spacing:.12em;text-transform:uppercase;font-weight:900}.onboarding,.home{min-height:100vh;padding:clamp(1.25rem,4vw,3.5rem);background:radial-gradient(circle at 80% 0,#d9f8e5,transparent 35%),#f4f8f5}.glass{background:#ffffffd9;border:1px solid #fff;border-radius:28px;box-shadow:0 24px 70px #335c4819}.lobby{max-width:560px;margin:8vh auto;padding:clamp(1.6rem,5vw,3rem)}h1{font-size:clamp(2rem,5vw,3.6rem);line-height:1;margin:.5rem 0 1rem}label{display:grid;gap:.45rem;margin:1rem 0;font-weight:800}input{border:1px solid #cadad1;border-radius:15px;padding:1rem;background:#f9fcfa;color:#18372b}.home{max-width:900px;margin:auto}.home>header{display:flex;justify-content:space-between;align-items:center}.avatar{display:grid;place-items:center;width:48px;height:48px;border-radius:50%;background:#25d366;color:#063420;font-weight:900}.small{width:42px;height:42px}.incoming,.dialer{padding:1.4rem;margin:1.5rem 0}.incoming{background:linear-gradient(135deg,#0b372c,#165945);color:white}.actions{display:flex;gap:.75rem;flex-wrap:wrap}.section-title,.session-row{display:flex;align-items:center;gap:1rem}.section-title{justify-content:space-between}.session-row{padding:1rem 0;border-bottom:1px solid #dce8e1}.session-row>div:nth-child(2){display:grid;gap:.25rem}.session-row small,.muted{color:#6f877b}.error{color:#ffb4b4}.toast{color:#a52336}.call-shell{min-height:100vh;background:radial-gradient(circle at top,#174a43,#071713 65%);color:#f4fbf8;display:grid;grid-template-rows:auto 1fr auto auto;gap:1rem;padding:1.25rem}.call-shell>header{display:flex;align-items:center;gap:.8rem}.call-shell small{display:block;color:#a9c7be}.call-shell video,.empty{width:100%;height:100%;min-height:340px;border-radius:28px;background:#0d2924;object-fit:cover;box-shadow:0 28px 80px #0008}.call-shell video.screen{object-fit:contain}.call-shell video.local{transform:scaleX(-1)}.empty{display:grid;place-items:center;align-content:center;gap:1rem}.hero{width:96px;height:96px;font-size:1.6rem}.call-shell nav{display:flex;justify-content:center;gap:.8rem;flex-wrap:wrap}.call-shell nav button{background:#183b35;color:white}.call-shell nav .end{background:#e94f5f}.test-note{margin:0;text-align:center;color:#789889;font-size:.72rem}.test-canvas,.remote-audio{position:absolute;width:1px;height:1px;overflow:hidden;opacity:.01;pointer-events:none}.test-canvas{right:0;bottom:0}.remote-audio{left:0;bottom:0}@media(max-width:600px){.call-shell{padding:.8rem}.call-shell video,.empty{min-height:55vh}.test-note{display:none}}
.media-stage{position:relative;min-height:340px;overflow:hidden;border-radius:28px;background:#0d2924}.main-media{position:absolute;inset:0;width:100%;height:100%;padding:0;border:0;border-radius:0;background:transparent}.main-media video{min-height:0;border-radius:0}.media-previews{position:absolute;z-index:4;top:14px;right:14px;display:flex;gap:8px;max-width:min(52%,420px);touch-action:none;cursor:grab;will-change:transform}.media-previews:active{cursor:grabbing}.mini-media{position:relative;width:clamp(112px,18vw,190px);aspect-ratio:16/10;padding:0;overflow:hidden;border:2px solid #8cd8aa;border-radius:16px;background:#10251c;box-shadow:0 10px 28px #0009;color:#fff}.mini-media video{min-height:0;border-radius:0;box-shadow:none}.mini-media span{position:absolute;left:8px;bottom:7px;padding:4px 7px;border-radius:999px;background:#03100cbf;font-size:10px}.preview-grip{position:absolute;right:-2px;bottom:-2px;display:grid;place-items:center;width:22px;height:22px;border-radius:7px;background:#8cd8aa;color:#092519;font-style:normal;pointer-events:none}.gesture-hint{margin:-.7rem 0 0;text-align:center;color:#8ba99b;font-size:.72rem;font-weight:700}
</style>

// apps/react/App.tsx
import { FormEvent, PointerEvent as ReactPointerEvent, useCallback, useEffect, useMemo, useRef, useState } from 'react';
import { AudioGrid, ModernMediasfuGeneric, useMediasfuHeadless } from 'mediasfu-reactjs';
import './app.css';
import './call-parity.css';

type Identity = { userId: string; displayName: string };
type CallType = 'audio' | 'video';
type Session = {
  id: string;
  hostUserId: string;
  targetUserId: string;
  displayName: string;
  meetingId: string;
  callType: CallType;
  status: 'ringing' | 'active' | 'ended';
  createdAt: string;
  updatedAt: string;
  endedAt?: string | null;
  endReason?: string | null;
};
type CallConfig =
  | { mode: 'create'; targetUserId: string; callType: CallType }
  | { mode: 'join'; session: Session; callType: CallType };
type ApiResult<T> = { success: true; data: T; session?: Session };
type MediaAction = () => Promise<{ ok: boolean; error?: string }>;
type VideoSurface = { stream: MediaStream; mode: 'screen' | 'remote' | 'local'; key: string };

const IDENTITY_KEY = 'mediasfu-familiar-call-identity';
const POLL_INTERVAL_MS = 1_500;
const PREVIEW_GAP = 14;

const clamp = (value: number, minimum: number, maximum: number) => Math.min(Math.max(value, minimum), maximum);

export function clampMiniOffset(
  offset: { x: number; y: number },
  stage: { width: number; height: number },
  preview: { width: number; height: number },
) {
  const baseLeft = Math.max(stage.width - preview.width - PREVIEW_GAP, 0);
  return {
    x: clamp(offset.x, -baseLeft, PREVIEW_GAP),
    y: clamp(offset.y, -PREVIEW_GAP, Math.max(stage.height - preview.height - PREVIEW_GAP, -PREVIEW_GAP)),
  };
}

async function request<T>(path: string, options?: RequestInit): Promise<T> {
  const response = await fetch(path, {
    ...options,
    headers: { 'content-type': 'application/json', ...(options?.headers || {}) },
  });
  const payload = await response.json().catch(() => ({}));
  if (!response.ok || payload.success === false) {
    throw new Error(payload.error || `Request failed (${response.status}).`);
  }
  return payload;
}

const listSessions = (userId: string) =>
  request<ApiResult<Session[]>>(`/api/users/${encodeURIComponent(userId)}/sessions`);

const initials = (value: string) => value.slice(0, 2).toUpperCase() || '??';

function otherUser(session: Session, identity: Identity) {
  return session.hostUserId === identity.userId ? session.targetUserId : session.hostUserId;
}

function StreamVideo({ stream, mirror }: { stream: MediaStream; mirror: boolean }) {
  const ref = useRef<HTMLVideoElement>(null);
  useEffect(() => {
    if (ref.current) ref.current.srcObject = stream;
    return () => {
      if (ref.current?.srcObject === stream) ref.current.srcObject = null;
    };
  }, [stream]);
  return <video ref={ref} muted={mirror} autoPlay playsInline className={mirror ? 'mirror' : ''} />;
}

function Onboarding({ onComplete }: { onComplete: (identity: Identity) => void }) {
  const [displayName, setDisplayName] = useState('');
  const [userId, setUserId] = useState('');
  const [error, setError] = useState('');
  const submit = (event: FormEvent) => {
    event.preventDefault();
    const identity = { displayName: displayName.trim(), userId: userId.trim() };
    if (!/^[A-Za-z0-9]{2,10}$/.test(identity.displayName)) {
      return setError('Use 2–10 letters or numbers for your display name.');
    }
    if (!/^[A-Za-z0-9_-]{2,64}$/.test(identity.userId)) {
      return setError('Use 2–64 letters, numbers, underscores, or hyphens for your user ID.');
    }
    sessionStorage.setItem(IDENTITY_KEY, JSON.stringify(identity));
    onComplete(identity);
  };
  return <main className="onboarding-shell">
    <section className="onboarding-card">
      <div className="brand-mark">M</div>
      <p className="eyebrow">MediaSFU familiar calls</p>
      <h1>Calls that feel instantly familiar.</h1>
      <p className="supporting">Choose how friends identify you. Calls happen from your contacts screen—room IDs stay behind the scenes.</p>
      <form onSubmit={submit}>
        <label>Display name<input autoFocus value={displayName} onChange={(event) => setDisplayName(event.target.value)} placeholder="Alex" /></label>
        <label>Your user ID<input value={userId} onChange={(event) => setUserId(event.target.value)} placeholder="alex-01" /></label>
        {error && <p className="notice" role="alert">{error}</p>}
        <button className="primary" type="submit">Continue to calls <span>→</span></button>
      </form>
      <small>Your app talks only to its own backend. MediaSFU API credentials never enter the browser.</small>
    </section>
  </main>;
}

function Home({
  identity, sessions, incoming, online, error, onCreate, onAccept, onDecline, onReset,
}: {
  identity: Identity;
  sessions: Session[];
  incoming: Session | null;
  online: boolean;
  error: string;
  onCreate: (targetUserId: string, callType: CallType) => void;
  onAccept: (session: Session) => void;
  onDecline: (session: Session) => void;
  onReset: () => void;
}) {
  const [target, setTarget] = useState('');
  const [callType, setCallType] = useState<CallType>('video');
  const [localError, setLocalError] = useState('');
  const submit = (event: FormEvent) => {
    event.preventDefault();
    const targetUserId = target.trim();
    if (!/^[A-Za-z0-9_-]{2,64}$/.test(targetUserId)) return setLocalError('Enter a valid target user ID.');
    if (targetUserId === identity.userId) return setLocalError('Choose another user to call.');
    setLocalError('');
    onCreate(targetUserId, callType);
  };
  return <main className="home-shell">
    <div className="ambient ambient-one" /><div className="ambient ambient-two" />
    <section className="home-content">
      <header className="home-header">
        <div><p className="eyebrow">Media calls</p><h1>Chats & calls</h1></div>
        <button className="identity-chip" onClick={onReset} title="Change identity">
          <span className="avatar">{initials(identity.displayName)}</span>
          <span><strong>{identity.displayName}</strong><small>@{identity.userId}</small></span>
        </button>
      </header>
      <div className={`connection-pill ${online ? '' : 'offline'}`}><i />{online ? 'Ready for calls' : 'Backend reconnecting…'}</div>

      {incoming && <article className="incoming-card" data-testid="incoming-call">
        <div className="incoming-person"><span className="avatar large">{initials(incoming.displayName)}</span><div><p className="eyebrow">Incoming {incoming.callType} call</p><h2>{incoming.displayName}</h2><span>@{incoming.hostUserId} is calling</span></div></div>
        <div className="incoming-actions">
          <button className="decline" onClick={() => onDecline(incoming)}>Decline</button>
          <button className="accept" onClick={() => onAccept(incoming)}>Accept call</button>
        </div>
      </article>}

      <div className="home-grid">
        <section className="composer-card">
          <div className="card-heading"><div><h2>Start a call</h2><p>Invite someone by their user ID</p></div><span className="phone-mark">☎</span></div>
          <form onSubmit={submit}>
            <label>Who would you like to call?<input value={target} onChange={(event) => setTarget(event.target.value)} placeholder="friend-user-id" /></label>
            <div className="call-type" role="group" aria-label="Call type">
              <button type="button" className={callType === 'video' ? 'selected' : ''} onClick={() => setCallType('video')}><span>▰</span> Video</button>
              <button type="button" className={callType === 'audio' ? 'selected' : ''} onClick={() => setCallType('audio')}><span>●</span> Audio</button>
            </div>
            {(localError || error) && <p className="notice" role="alert">{localError || error}</p>}
            <button className="primary" type="submit">Call now <span>→</span></button>
          </form>
        </section>

        <section className="recent-card">
          <div className="card-heading"><div><h2>Recent calls</h2><p>Session details only—never call media</p></div><span className="count">{sessions.length}</span></div>
          <div className="session-list">
            {sessions.length ? sessions.map((session) => <button className="session-row" key={session.id} disabled={session.status === 'ended'} onClick={() => onAccept(session)}>
              <span className="avatar">{initials(otherUser(session, identity))}</span>
              <span className="session-copy"><strong>{otherUser(session, identity)}</strong><small>{session.callType === 'audio' ? 'Audio' : 'Video'} · {session.status === 'ended' ? 'Ended' : session.status === 'active' ? 'Connected' : 'Ringing'}</small></span>
              <time>{new Date(session.updatedAt || session.createdAt).toLocaleTimeString([], { hour: '2-digit', minute: '2-digit' })}</time>
            </button>) : <div className="empty-history"><span>☏</span><strong>Your recent calls appear here</strong><p>Call a contact to get started.</p></div>}
          </div>
        </section>
      </div>
    </section>
  </main>;
}

export default function App() {
  const room = useMediasfuHeadless();
  const [identity, setIdentity] = useState<Identity | null>(() => {
    try { return JSON.parse(sessionStorage.getItem(IDENTITY_KEY) || 'null'); } catch { return null; }
  });
  const [sessions, setSessions] = useState<Session[]>([]);
  const [incoming, setIncoming] = useState<Session | null>(null);
  const [online, setOnline] = useState(true);
  const [callConfig, setCallConfig] = useState<CallConfig | null>(null);
  const [activeSession, setActiveSession] = useState<Session | null>(null);
  const [notice, setNotice] = useState('');
  const [demoActive, setDemoActive] = useState(false);
  const roomRequestRef = useRef<Promise<any> | null>(null);
  const roleAssignmentRef = useRef<CallConfig | null>(null);
  const mediaInitializationRef = useRef<CallConfig | null>(null);
  const activeSessionRef = useRef<Session | null>(null);
  const canvasRef = useRef<HTMLCanvasElement>(null);
  const demoTimerRef = useRef<number | null>(null);
  const demoStreamRef = useRef<MediaStream | null>(null);
  const [focusIndex, setFocusIndex] = useState(0);
  const [miniOffset, setMiniOffset] = useState({ x: 0, y: 0 });
  const stageRef = useRef<HTMLElement>(null);
  const miniRef = useRef<HTMLDivElement>(null);
  const stageSizeRef = useRef({ width: 0, height: 0 });
  const miniSizeRef = useRef({ width: 0, height: 0 });
  const dragRef = useRef<{ pointerId: number; startX: number; startY: number; originX: number; originY: number } | null>(null);

  useEffect(() => { activeSessionRef.current = activeSession; }, [activeSession]);

  useEffect(() => {
    if (!identity) return;
    let mounted = true;
    const poll = async () => {
      try {
        const payload = await listSessions(identity.userId);
        if (!mounted) return;
        const next = [...payload.data].sort((a, b) => Date.parse(b.updatedAt) - Date.parse(a.updatedAt));
        setSessions(next);
        setOnline(true);
        const ringing = next.find((session) => session.targetUserId === identity.userId && session.status === 'ringing');
        setIncoming(callConfig ? null : ringing || null);
        const current = activeSessionRef.current;
        if (current) {
          const updated = next.find((session) => session.id === current.id);
          if (updated) setActiveSession(updated);
          if (updated?.status === 'ended') {
            setCallConfig(null); room.updateSourceParameters({});
          }
        }
      } catch { if (mounted) setOnline(false); }
    };
    poll();
    const timer = window.setInterval(poll, POLL_INTERVAL_MS);
    return () => { mounted = false; window.clearInterval(timer); };
  }, [identity, callConfig]);

  const surfaces = useMemo<VideoSurface[]>(() => {
    const next: VideoSurface[] = [];
    if (room.screenShare.stream) next.push({ stream: room.screenShare.stream, mode: 'screen', key: `screen-${room.screenShare.stream.id}` });
    if (room.remoteVideos[0]?.stream) next.push({ stream: room.remoteVideos[0].stream, mode: 'remote', key: `remote-${room.remoteVideos[0].producerId || room.remoteVideos[0].stream.id}` });
    if (room.localVideo) next.push({ stream: room.localVideo, mode: 'local', key: `local-${room.localVideo.id}` });
    return next;
  }, [room.screenShare, room.remoteVideos, room.localVideo]);
  const screenActive = surfaces[0]?.mode === 'screen';
  const normalizedFocus = screenActive ? 0 : Math.min(focusIndex, Math.max(surfaces.length - 1, 0));
  const primary = surfaces[normalizedFocus] || null;
  const previews = surfaces.filter((_, index) => index !== normalizedFocus);
  const canSwapFocus = !screenActive && surfaces.length > 1;

  useEffect(() => {
    if (screenActive || focusIndex >= surfaces.length) setFocusIndex(0);
  }, [focusIndex, screenActive, surfaces.length]);

  const measurePreview = useCallback(() => {
    const stage = stageRef.current?.getBoundingClientRect();
    const preview = miniRef.current?.getBoundingClientRect();
    if (!stage || !preview) return;
    stageSizeRef.current = { width: stage.width, height: stage.height };
    miniSizeRef.current = { width: preview.width, height: preview.height };
    setMiniOffset((current) => clampMiniOffset(current, stageSizeRef.current, miniSizeRef.current));
  }, []);

  useEffect(() => {
    measurePreview();
    window.addEventListener('resize', measurePreview);
    const observer = typeof ResizeObserver === 'function' ? new ResizeObserver(measurePreview) : null;
    if (stageRef.current) observer?.observe(stageRef.current);
    if (miniRef.current) observer?.observe(miniRef.current);
    return () => { observer?.disconnect(); window.removeEventListener('resize', measurePreview); };
  }, [measurePreview, previews.length]);

  const swapFocus = () => {
    if (!canSwapFocus) return;
    setFocusIndex((current) => current === 0 ? 1 : 0);
  };
  const startMiniDrag = (event: ReactPointerEvent<HTMLDivElement>) => {
    dragRef.current = { pointerId: event.pointerId, startX: event.clientX, startY: event.clientY, originX: miniOffset.x, originY: miniOffset.y };
    event.currentTarget.setPointerCapture?.(event.pointerId);
    event.preventDefault();
  };
  const moveMini = (event: ReactPointerEvent<HTMLDivElement>) => {
    const drag = dragRef.current;
    if (!drag || drag.pointerId !== event.pointerId) return;
    setMiniOffset(clampMiniOffset(
      { x: drag.originX + event.clientX - drag.startX, y: drag.originY + event.clientY - drag.startY },
      stageSizeRef.current,
      miniSizeRef.current,
    ));
  };
  const stopMiniDrag = (event: ReactPointerEvent<HTMLDivElement>) => {
    if (dragRef.current?.pointerId !== event.pointerId) return;
    event.currentTarget.releasePointerCapture?.(event.pointerId);
    dragRef.current = null;
  };

  const preJoinOptions = useMemo(() => {
    if (!identity || !callConfig) return undefined;
    return callConfig.mode === 'create'
      ? { action: 'create' as const, userName: identity.displayName, duration: 30, capacity: 2, eventType: 'conference' as const }
      : { action: 'join' as const, userName: identity.displayName, meetingID: callConfig.session.meetingId };
  }, [identity, callConfig]);

  const createMediaSFURoom = async () => {
    if (!identity || callConfig?.mode !== 'create') return { success: false, data: { error: 'Call setup is incomplete.' } };
    if (!roomRequestRef.current) roomRequestRef.current = request<ApiResult<unknown>>('/api/rooms/create', {
      method: 'POST',
      body: JSON.stringify({
        hostUserId: identity.userId, targetUserId: callConfig.targetUserId,
        displayName: identity.displayName, duration: 30, capacity: 2,
        eventType: 'conference', callType: callConfig.callType,
      }),
    });
    try {
      const payload = await roomRequestRef.current;
      setActiveSession(payload.session || null);
      setSessions((current) => payload.session ? [payload.session, ...current.filter((item) => item.id !== payload.session.id)] : current);
      return { success: true, data: payload.data };
    } catch (error) {
      const message = error instanceof Error ? error.message : 'Could not create the call.';
      setNotice(message);
      return { success: false, data: { error: message } };
    }
  };

  const joinMediaSFURoom = async () => {
    if (!identity || callConfig?.mode !== 'join') return { success: false, data: { error: 'Call setup is incomplete.' } };
    if (!roomRequestRef.current) roomRequestRef.current = request<ApiResult<unknown>>('/api/rooms/join', {
      method: 'POST',
      body: JSON.stringify({ sessionId: callConfig.session.id, userId: identity.userId, displayName: identity.displayName }),
    });
    try {
      const payload = await roomRequestRef.current;
      setActiveSession(payload.session || callConfig.session);
      return { success: true, data: payload.data };
    } catch (error) {
      const message = error instanceof Error ? error.message : 'Could not join the call.';
      setNotice(message);
      return { success: false, data: { error: message } };
    }
  };

  const updateSourceParameters = (parameters: any) => {
    const next = parameters || {};
    room.updateSourceParameters(next);
    if (callConfig && roleAssignmentRef.current !== callConfig && typeof next.updateIslevel === 'function') {
      next.updateIslevel(callConfig.mode === 'create' ? '2' : '1');
      roleAssignmentRef.current = callConfig;
    }
    if (callConfig && next.validated && mediaInitializationRef.current !== callConfig) {
      mediaInitializationRef.current = callConfig;
      const actions: Promise<unknown>[] = [];
      if (!next.audioAlreadyOn && typeof next.clickAudio === 'function') actions.push(room.controls.toggleMic());
      if (callConfig.callType === 'video' && !next.videoAlreadyOn && typeof next.clickVideo === 'function') actions.push(room.controls.toggleCamera());
      Promise.allSettled(actions).catch(() => undefined);
    }
  };

  const beginCall = (config: CallConfig) => {
    setNotice(''); setIncoming(null); setActiveSession(config.mode === 'join' ? config.session : null);
    roomRequestRef.current = null; roleAssignmentRef.current = null; mediaInitializationRef.current = null;
    room.updateSourceParameters({}); setCallConfig(config);
  };

  const decline = async (session: Session) => {
    if (!identity) return;
    try {
      await request(`/api/sessions/${encodeURIComponent(session.id)}/end`, {
        method: 'POST', body: JSON.stringify({ userId: identity.userId, reason: 'declined' }),
      });
      setIncoming(null);
    } catch (error) { setNotice(error instanceof Error ? error.message : 'Could not decline the call.'); }
  };

  const run = async (action: MediaAction) => {
    const result = await action();
    setNotice(result.ok ? '' : result.error || 'The action could not be completed.');
  };

  const toggleDemoVideo = async () => {
    if (demoActive) {
      if (demoTimerRef.current) window.clearInterval(demoTimerRef.current);
      demoTimerRef.current = null;
      demoStreamRef.current?.getTracks().forEach((track) => track.stop());
      demoStreamRef.current = null;
      const result = await room.produce.stop('video');
      setDemoActive(false); setNotice(result.ok ? '' : result.error || 'Could not stop test media.');
      return;
    }
    const canvas = canvasRef.current;
    const context = canvas?.getContext('2d');
    if (!canvas || !context) return setNotice('The media test canvas is unavailable.');
    let frame = 0;
    const draw = () => {
      frame += 1;
      const hue = (frame * 2) % 360;
      const gradient = context.createLinearGradient(0, 0, canvas.width, canvas.height);
      gradient.addColorStop(0, `hsl(${hue} 50% 13%)`);
      gradient.addColorStop(1, `hsl(${(hue + 70) % 360} 74% 38%)`);
      context.fillStyle = gradient; context.fillRect(0, 0, canvas.width, canvas.height);
      context.fillStyle = '#effff7'; context.font = '800 72px Inter, sans-serif';
      context.fillText('MediaSFU live media', 76, 250);
      context.font = '500 34px Inter, sans-serif';
      context.fillText(`${identity?.displayName || 'Caller'} · WebRTC test producer`, 80, 320);
      context.beginPath(); context.arc(130 + ((frame * 9) % 980), 520, 54, 0, Math.PI * 2);
      context.fillStyle = '#5bf0a4'; context.fill();
    };
    draw(); demoTimerRef.current = window.setInterval(draw, 100);
    const result = await room.produce.canvas(canvas, 15);
    if (!result.ok) {
      if (demoTimerRef.current) window.clearInterval(demoTimerRef.current);
      demoTimerRef.current = null; return setNotice(result.error || 'Could not publish test media.');
    }
    demoStreamRef.current = result.stream; setDemoActive(true); setNotice('');
  };

  const finishCall = async () => {
    if (demoActive) await toggleDemoVideo();
    if (room.ready) await room.controls.leave().catch(() => undefined);
    if (activeSession?.id && identity) {
      try {
        await request(`/api/sessions/${encodeURIComponent(activeSession.id)}/end`, {
          method: 'POST', body: JSON.stringify({ userId: identity.userId, reason: 'user_ended' }),
        });
      } catch (error) { setNotice(error instanceof Error ? error.message : 'Could not close the call session.'); }
    }
    setCallConfig(null); setActiveSession(null); roomRequestRef.current = null;
    roleAssignmentRef.current = null; mediaInitializationRef.current = null; room.updateSourceParameters({});
  };

  useEffect(() => () => {
    if (demoTimerRef.current) window.clearInterval(demoTimerRef.current);
    demoStreamRef.current?.getTracks().forEach((track) => track.stop());
  }, []);

  if (!identity) return <Onboarding onComplete={setIdentity} />;

  if (!callConfig) return <Home
    identity={identity} sessions={sessions} incoming={incoming} online={online} error={notice}
    onCreate={(targetUserId, callType) => beginCall({ mode: 'create', targetUserId, callType })}
    onAccept={(session) => beginCall({ mode: 'join', session, callType: session.callType || 'video' })}
    onDecline={decline}
    onReset={() => { sessionStorage.removeItem(IDENTITY_KEY); setIdentity(null); setSessions([]); }}
  />;

  const peerName = callConfig.mode === 'create' ? callConfig.targetUserId : otherUser(callConfig.session, identity);
  const callState = notice ? 'Connection issue' : room.ready ? 'Connected' : activeSession?.status === 'ringing' ? 'Ringing…' : 'Connecting securely…';

  return <>
    <div className="engine" aria-hidden>
      <ModernMediasfuGeneric
        connectMediaSFU returnUI={false} noUIPreJoinOptions={preJoinOptions}
        createMediaSFURoom={createMediaSFURoom} joinMediaSFURoom={joinMediaSFURoom}
        sourceParameters={room.sourceParameters} updateSourceParameters={updateSourceParameters}
        onMediaChanged={room.onMediaChanged}
      />
    </div>
    <main className="call-shell">
      <header className="call-header">
        <div className="call-peer"><span className="avatar large">{initials(peerName)}</span><div><strong>{peerName}</strong><small>{callConfig.callType === 'audio' ? 'Audio call' : 'Video call'} · {callState}</small></div></div>
        <span className={`live-state ${room.ready ? 'ready' : ''}`}><i />{room.ready ? 'Live' : 'Securing call'}</span>
      </header>
      <section ref={stageRef} className={`media-stage ${primary?.mode || 'empty'}`} data-focus-index={normalizedFocus}>
        {primary
          ? <button type="button" className="main-media" onDoubleClick={swapFocus} aria-label="Main call media. Double-click or double-tap to swap with the mini preview."><StreamVideo stream={primary.stream} mirror={primary.mode === 'local' && !demoActive} /></button>
          : <div className="empty-state"><span className="avatar hero">{initials(peerName)}</span><strong>{activeSession?.status === 'ringing' ? `Calling ${peerName}…` : 'Preparing your private call'}</strong><p>{room.readiness.reason || 'Waiting for MediaSFU media readiness.'}</p></div>}
        <span className="media-badge">{primary?.mode === 'screen' ? 'Screen share' : primary?.mode === 'remote' ? peerName : primary?.mode === 'local' ? (demoActive ? 'Media test' : 'You') : 'Waiting'}</span>
        {previews.length > 0 && <div ref={miniRef} className="media-previews" style={{ transform: `translate3d(${miniOffset.x}px, ${miniOffset.y}px, 0)` }} onPointerDown={startMiniDrag} onPointerMove={moveMini} onPointerUp={stopMiniDrag} onPointerCancel={stopMiniDrag} aria-label="Other call views. Drag to move.">
          {previews.map((surface, index) => <button type="button" key={surface.key} className="mini-media" onDoubleClick={index === 0 ? swapFocus : undefined} onClick={() => { if (screenActive) return; const sourceIndex = surfaces.indexOf(surface); if (sourceIndex >= 0) setFocusIndex(sourceIndex); }} aria-label={index === 0 ? 'Mini call media. Double-click or double-tap to swap with the main media.' : `Focus call preview ${index + 1}`}><StreamVideo stream={surface.stream} mirror={surface.mode === 'local' && !demoActive} /><span>{surface.mode === 'local' ? 'You' : surface.mode === 'remote' ? peerName : 'Screen'}</span></button>)}
          <i className="preview-grip" aria-hidden>⋮⋮</i>
        </div>}
      </section>
      {previews.length > 0 && <p className="gesture-hint">Double-tap to swap views · Drag the small view to move it</p>}
      {notice && <p className="notice floating" role="alert">{notice}</p>}
      <nav className="call-controls" aria-label="Call controls">
        <button disabled={!room.ready} onClick={() => run(room.controls.toggleMic)} className={room.micOn ? 'control active' : 'control'}><span>{room.micOn ? '●' : '○'}</span>{room.micOn ? 'Mute' : 'Unmute'}</button>
        {callConfig.callType === 'video' && <button disabled={!room.ready} onClick={() => run(room.controls.toggleCamera)} className={room.cameraOn ? 'control active' : 'control'}><span>▰</span>{room.cameraOn ? 'Camera off' : 'Camera on'}</button>}
        <button disabled={!room.ready} onClick={() => run(room.controls.toggleScreenShare)} className="control"><span>⇧</span>Share</button>
        <button disabled={!room.ready} onClick={toggleDemoVideo} className={demoActive ? 'control active test-control' : 'control test-control'}><span>◇</span>{demoActive ? 'Stop test' : 'Test media'}</button>
        <button onClick={finishCall} className="control end"><span>☎</span>End</button>
      </nav>
      <p className="test-note">“Test media” publishes an animated canvas through the real room for repeatable two-device verification.</p>
      <div className="audio-mount" aria-hidden><AudioGrid componentsToRender={room.audioComponents} /></div>
      <canvas ref={canvasRef} width={1280} height={720} aria-hidden className="test-canvas" />
    </main>
  </>;
}
